<script setup lang="ts">
import GenericBadge from "~/components/hint/badge/GenericBadge.vue";
</script>

<template>
  <GenericBadge icon="carbon:ai-generate" left-color="bg-gray-600 dark:bg-gray-200"
    right-color="bg-green-300 dark:bg-green-600" left-text="AI-powered" right-text="API"
    tooltip="Contents are generated by LLM. " />
</template>

<style scoped></style>